baseURL = "https://javad5087.github.io/weather/"
publishDir = "docs"
languageCode = "fa-IR"
title = "آب و هوای کردستان"

disableKinds = ["taxonomy","term"]

[params]
author = "Javad Sajjadi"
description = "پیش بینی آب و هوای شهرهای استان کردستان"

[markup]
defaultMarkdownHandler = "goldmark"
